spring.application.name=lab2

# Database configuration
spring.datasource.url=jdbc:postgresql://78.46.199.126:5014/postgres?user=postgres&password=9XMTu1e96A7PIL7YvhnuqXQvC6uYf7K6QEG0l1niy3VA0uf7uUi5gf9HCmfyYcUG
spring.jpa.hibernate.ddl-auto=update

# JPA configuration
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

default.admin.username=admin
default.admin.password=admin12345

# Narayana transaction manager configuration
spring.jta.enabled=false
