spring.application.name=lab2

# Database configuration
spring.datasource.url=jdbc:postgresql://78.46.199.126:5014/postgres?user=postgres&password=9XMTu1e96A7PIL7YvhnuqXQvC6uYf7K6QEG0l1niy3VA0uf7uUi5gf9HCmfyYcUG
# spring.datasource.url=jdbc:postgresql://localhost:5014/postgres?user=postgres&password=9XMTu1e96A7PIL7YvhnuqXQvC6uYf7K6QEG0l1niy3VA0uf7uUi5gf9HCmfyYcUG
spring.jpa.hibernate.ddl-auto=update

# JPA configuration
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
jwt.secret=ABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBAABOBA
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

default.admin.username=admin
default.admin.password=admin12345

# Narayana transaction manager configuration
spring.jta.enabled=false

# Added for Task async-notifications_2025-04-28_1
# RabbitMQ Configuration
spring.rabbitmq.host=178.156.135.29
spring.rabbitmq.port=30072
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JMS (using RabbitMQ JMS Client - needs specific ConnectionFactory config in Java)
# spring.jms.???

# WebSocket/STOMP Configuration
spring.websocket.stomp.relay.host=178.156.135.29
spring.websocket.stomp.relay.port=30074
spring.websocket.stomp.relay.system-login=guest
spring.websocket.stomp.relay.system-passcode=guest
spring.websocket.stomp.relay.client-login=guest
spring.websocket.stomp.relay.client-passcode=guest
# spring.websocket.???
# End Task async-notifications_2025-04-28_1

# Added for Task promotion-emails-deactivation_2025-04-28_1
# JCA SMTP Resource Adapter Configuration
jca.mail.sender-email=${MAIL_SENDER:zphrmynxajsw@mail-craft.ru}
jca.mail.host=smtp.mail.ru
jca.mail.port=465
jca.mail.protocol=smtp
jca.mail.username=${MAIL_USERNAME}
jca.mail.password=${MAIL_PASSWORD}
# Promotion Settings
promotion.reminder.days-before=0
promotion.scheduler.cron=0 * * * * *
